### ISSUE TITLE
Closes silently given CFBundleIconFile without ".icns" extension

### ISSUE THREAD

**Issue by symbioquine** [tofi86/universalJavaApplicationStub#75] opened 2019-10-13 18:23 UTC
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**

Both of the following `CFBundleIconFile` configurations seem to be valid in one's `Info.plist` file - shows the icon in Finder and such correctly.

```xml
<key>CFBundleIconFile</key>    <string>icon.icns</string>
```

```xml
<key>CFBundleIconFile</key>    <string>icon</string>
```

However, the later - without the ".icns" extension - causes `universalJavaApplicationStub` to silently exit instead of showing the expected dialog.

**Steps to reproduce the issue/enhancement:**

1. Take an otherwise working app bundle which uses `universalJavaApplicationStub` and change the `CFBundleIconFile` key in its `Info.plist` file to remove the ".icns" extension.
2. Try launching the bundle under conditions that should show a dialog - such as the required Java version not being available.

**What is the expected behavior?**

One or more of the following;

* `universalJavaApplicationStub` should still show dialogs - perhaps without the icon
* `universalJavaApplicationStub` should explicitly complain in the syslog if the icon is specified in an invalid way
* The documentation should explicitly call out this gotcha since it is unintuitive and moderately hard to troubleshoot

**What is the current behavior?**

`universalJavaApplicationStub` silently exits instead of showing the expected dialog.

**Do you have screenshots, GIFs, demos or samples which demonstrate the problem or enhancement?**

N/A

**What is the motivation / use case for changing the behavior?**

Make onboarding with this utility more fool-proof.

**Please tell us about your environment:**

- universalJavaApplicationStub version: 3.0.4
- Mac OS version: MacOSX Mojave 10.14
- Java version(s): N/A - Current branch of testing uses OS image prior to installation of any JVM

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

N/A

**Comment by tofi86** [comment] 2019-10-14 21:58
Thanks for the report. Looks legit. I will have a closer look at the weekend.

**Comment by tofi86** [comment] 2019-12-08 20:08
This seems to be an issue with Oracle's Java. In my tests, it works well without the file type extension in AdoptOpenJDK 11 for example, but fails as described in Oralce JDK 8 or 9.

So technically it's not an issue with this launcher script.

I _could_ add a function which add's `.icns` to icons which don't have an `.icns` extension, but that would be wrong as well, because also `.png` is an allowed filetype for the `CFBundleIconFile` key.

@symbioquine would you agree if I close this as `invalid`/`out-of-scope`?

**Comment by symbioquine** [comment] 2019-12-08 20:21
@tofi86 That conclusion is a little surprising to me since I was testing under conditions where no JVM/JRE has ever been installed. I'd assumed this behavior is an artifact of how this tool uses AppleScript for displaying dialogs prior to invoking Java. Would you be willing to share your test methodology which shows the behavior to be specific to a particular Java distribution?

**Comment by tofi86** [comment] 2019-12-08 22:58
Oh, so I experienced and investigated _another_ issue while testing this and misunderstood your report. Sorry for that.

I read too quickly and interpreted "dialog" as your application GUI. So I changed the `CFBundleIconFile` in my [demo app](https://github.com/tofi86/universalJavaApplicationStubDemo) and removed the `.icns` extension and then tried to start the app.

Using AdoptOpen JDK this worked fine and the GUI was displayed. Then I switched to Oracle JDK and the GUI didn't show anymore. At this point I was sure I hit your issue and stopped investigating.

I will have another look in the next couple of days. Sorry for the delay.

**Comment by tofi86** [comment] 2019-12-09 21:13
Okay, I tested this again, and I was able to reproduce the issue.

I pushed a fix to the `develop` branch. Could you probably test it as well?

**Comment by tofi86** [comment] 2019-12-09 21:15
Just out of curiosity: do you also get a system security events dialog before the AppleScript dialog? => #77

**Comment by tofi86** [comment] 2019-12-09 21:17
> I pushed a fix to the `develop` branch.

To be a bit more verbose: The script now checks for the `CFBundleIconFile` in the Resources folder: if present, displays dialogs with icon. If not ending with `*.icns` but present with `.icns` in the Resources folder: displays dialogs with icon. In any other case, the dialog is displayed without an icon.

**Closed** 2019-12-09 21:31 UTC
Labels: bug

**Comment by symbioquine** [comment] 2019-12-12 06:46
Thanks! Confirming the updated version appears to have solved the problem for me - the dialog works regardless of whether the .icns extension is specified.

> Just out of curiosity: do you also get a system security events dialog before the AppleScript dialog?

I'm not sure. I wasn't seeing it in my latest testing this evening, but I think I've seen it in the past.

**Comment by tofi86** [comment] 2019-12-12 17:14
Perfect, thanks for testing!
