### ISSUE TITLE
Incorrect handling of spaces in the stub

### ISSUE THREAD

**Issue by Azhrei** [tofi86/universalJavaApplicationStub#40] opened 2017-01-10 06:25 UTC
I have a Plist file in which the $JAVAROOT value will contain spaces.  Unfortunately, when the properties are eval'd to replace variable values, they don't have the correct quotes added around them so they'll work on the eventual command line.

Thinking about this, I decided adding double quotes was the wrong solution anyway (well, thinking about it AND doing some testing).  What if the user put double quotes in their pathname to the app?  Yeah, I know they shouldn't, but USERS don't know they shouldn't.  (Sigh.)

So I came up with the following snippet for the JVMOptions variable, around line 171 in the latest version.

```
JVMOptions=`$PL -c "print ${JavaKey}:Properties" "${InfoPlistFile}" 2> /dev/null | while read a b c; do [[ "$b" == '=' ]] && echo -n "-D$a=$(eval printf "%q" "$c") " ; done`
```

Since that code contains the `eval`, be sure to comment out the following line that does `eval echo ...` (it's no longer needed).

In my own version of the script I have changed some other nit-picky things (you'll notice I used [[ ]] instead of [ ] in my code), but those don't have any effect on the functionality so I won't mention them here.  At some point, I'll fork this repo and generate a pull request, but that's down the road a bit (and I've got deadlines to work on!).

One last thing...  I have an app built for 1.6 that I want to run under 1.8.  However, it uses Apple's `com.apple.eawt.CocoaComponent` class.  Does anyone know off-hand where I can get that class so I can put it on the class path for my app?  It was Apple-specific and went away in 1.7 so I need a replacement.  Apple never open sourced it and its functionality got rolled up into the theme that shipped with 1.7 (or maybe 1.8; I think there was a time that the API just disappeared for awhile while the OpenJDK folks worked on implementing it).

Anyway, I appreciate all of the effort on this project!  I'm hoping to get this old Java 1.6 app running!

**Comment by Azhrei** [comment] 2017-01-10 06:42
Never mind about the com.apple.eawt stuff.  Google found it pretty quickly and it turns out I've got a copy of the library under `/usr/share/java/Stubs` already.  Adding it to the CLASSPATH got me a little further, but my app still throwing exceptions...

**Comment by tofi86** [comment] 2017-01-10 09:04
> Never mind about the com.apple.eawt stuff. Google found it pretty quickly and it turns out I've got a copy of the library under /usr/share/java/Stubs already. Adding it to the CLASSPATH got me a little further, but my app still throwing exceptions...

Okay, great! Otherwise you can also find it on Maven: https://mvnrepository.com/artifact/com.apple/AppleJavaExtensions

> Anyway, I appreciate all of the effort on this project! I'm hoping to get this old Java 1.6 app running!

Thanks man! Whish you luck! Let me know if you ran into any more problems!

> In my own version of the script I have changed some other nit-picky things (you'll notice I used [[ ]] instead of [ ] in my code), but those don't have any effect on the functionality so I won't mention them here. At some point, I'll fork this repo and generate a pull request, but that's down the road a bit (and I've got deadlines to work on!).

Yeah, looking forward to your contribution! The codebase possibly grew a bit too quick, and with the change from `#!/bin/sh` to `#!/bin/bash` in latest 2.0 release things can be implemented easier or in better ways now... Unfortunately I haven't had time for the big refactoring with 2.0... :-(

> I have a Plist file in which the $JAVAROOT value will contain spaces. Unfortunately, when the properties are eval'd to replace variable values, they don't have the correct quotes added around them so they'll work on the eventual command line.

I think this is a duplicate of long lasting issue #14. Unfortunately I didn't find a good attempt to solve it for 2.0.

Anyways, I'm closing this issue in favor of #14 and we'll continue discussion over there...

**Closed by tofi86** 2017-01-10 09:04 UTC
